In [38]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
df = pd.read_csv('car data.csv')
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [3]:
df.drop_duplicates(inplace=True)

In [4]:
df.describe()

              Year  Selling_Price  Present_Price     Driven_kms       Owner
count   299.000000     299.000000     299.000000     299.000000  299.000000
mean   2013.615385       4.589632       7.541037   36916.752508    0.043478
std       2.896868       4.984240       8.566332   39015.170352    0.248720
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.850000       1.200000   15000.000000    0.000000
50%    2014.000000       3.510000       6.100000   32000.000000    0.000000
75%    2016.000000       6.000000       9.840000   48883.500000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [5]:
df.drop(columns=['Car_Name','Owner'],inplace=True)

In [6]:
df['Selling_type'] = df['Selling_type'].map({"Dealer":0,"Individual":1})

In [8]:
df['Transmission'] = df['Transmission'].map({"Manual":0,"Automatic":1})

In [10]:
fuel_dummies = pd.get_dummies(df['Fuel_Type'], prefix='Fuel', dtype=int)

In [11]:
fuel_dummies = fuel_dummies.drop('Fuel_CNG',axis=1)
fuel_dummies.head()

   Fuel_Diesel  Fuel_Petrol
0            0            1
1            1            0
2            0            1
3            0            1
4            1            0

In [12]:
df = pd.concat([df, fuel_dummies],axis=1)

In [13]:
df.drop('Fuel_Type',axis=1,inplace=True)

In [14]:
df.to_csv('car_cleaned_data.csv',index=False)

In [15]:
x = df[['Year', 'Present_Price', 'Driven_kms', 'Selling_type',
       'Transmission', 'Fuel_Diesel', 'Fuel_Petrol']]
y = df['Selling_Price']

In [17]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [19]:
model = LinearRegression()

In [20]:
model.fit(x_train,y_train)

LinearRegression()

In [21]:
y_pred = model.predict(x_test)

In [22]:
results = pd.DataFrame({
    'Actual Price': y_test,
    'Predicted Price': y_pred
})

results.head(10)

     Actual Price  Predicted Price
283          8.99         7.499023
267          8.35         7.810565
166          0.45         1.396367
9            7.45         7.023967
78           5.25        11.162212
280          5.25         4.542425
95           5.85         8.484464
111          1.15         1.724838
5            9.25         8.833508
175          0.38        -0.930679

In [31]:
model.score(x_train,y_train)

0.9041591574302968

In [32]:
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

Mean Absolute Error: 1.414025842602619

In [33]:
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 5.9433608100681194

In [34]:
rmse = np.sqrt(mse)
print("Root Mean Squared Error:", rmse)

Root Mean Squared Error: 2.4379009024298175

In [35]:
r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

R2 Score: 0.7693981941896499

In [37]:
print("Training Score:", model.score(x_train,y_train))
print("Testing Score:", model.score(x_test,y_test))

Training Score: 0.9041591574302968
Testing Score: 0.7693981941896499